# Generated by Django 5.2.1 on 2025-05-23 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acueducto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lectura', models.DateField(auto_now_add=True)),
                ('lectura', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='acueducto.useracueducto')),
            ],
            options={
                'ordering': ['-fecha_lectura'],
            },
        ),
    ]
