# Generated by Django 5.2.1 on 2025-05-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acueducto', '0002_historicolectura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicolectura',
            name='fecha_lectura',
            field=models.DateField(),
        ),
    ]
