# Generated by Django 5.2.1 on 2025-05-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acueducto', '0003_alter_historicolectura_fecha_lectura'),
    ]

    operations = [
        migrations.AddField(
            model_name='useracueducto',
            name='categoria',
            field=models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial')], default='residencial', max_length=20),
        ),
        migrations.AddField(
            model_name='useracueducto',
            name='zona',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
