# Generated by Django 5.2.1 on 2025-05-23 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acueducto', '0004_useracueducto_categoria_useracueducto_zona'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('lectura_tomada', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acueducto.useracueducto')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('usuarios', models.ManyToManyField(through='acueducto.OrdenRuta', to='acueducto.useracueducto')),
            ],
        ),
        migrations.AddField(
            model_name='ordenruta',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acueducto.ruta'),
        ),
        migrations.AlterUniqueTogether(
            name='ordenruta',
            unique_together={('ruta', 'orden')},
        ),
    ]
