# Generated by Django 5.2.1 on 2025-05-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acueducto', '0005_ordenruta_ruta_ordenruta_ruta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
