# Generated by Django 5.2.1 on 2025-05-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acueducto', '0006_ruta_fecha_finalizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='useracueducto',
            name='credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='useracueducto',
            name='credito_descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='useracueducto',
            name='otros_gastos_descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='useracueducto',
            name='otros_gastos_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
