# Generated by Django 4.2.1 on 2025-05-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acueducto', '0007_useracueducto_credito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useracueducto',
            name='date',
        ),
        migrations.AddField(
            model_name='useracueducto',
            name='fecha_ultima_lectura',
            field=models.DateField(blank=True, null=True),
        ),
    ]
