# Generated by Django 4.2.1 on 2025-05-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acueducto', '0008_remove_useracueducto_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useracueducto',
            name='numero_de_medidor',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
