# Generated by Django 5.2.1 on 2025-05-28 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acueducto', '0009_useracueducto_numero_de_medidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('clave', models.CharField(default='main', max_length=50, primary_key=True, serialize=False)),
                ('ultimo_numero_factura', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(help_text='Número único consecutivo de la factura', max_length=20, unique=True)),
                ('fecha_emision', models.DateField()),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('lectura_actual', models.FloatField(blank=True, null=True)),
                ('lectura_anterior', models.FloatField(blank=True, null=True)),
                ('consumo_m3', models.FloatField(blank=True, null=True)),
                ('costo_consumo_agua', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credito_aplicado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('otros_gastos_aplicados', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_factura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='acueducto.useracueducto')),
            ],
            options={
                'ordering': ['-fecha_emision', '-numero_factura'],
            },
        ),
    ]
