# Generated by Django 4.2.1 on 2025-07-17 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acueducto', '0009_useracueducto_numero_de_medidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.IntegerField(unique=True)),
                ('fecha_emision', models.DateField()),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('consumo', models.FloatField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf_generado', models.BooleanField(default=False)),
                ('email_enviado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='acueducto.useracueducto')),
            ],
            options={
                'ordering': ['-fecha_emision', '-consecutivo'],
            },
        ),
    ]
