# Generated by Django 4.2.1 on 2025-07-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acueducto', '0010_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='useracueducto',
            name='credito_cuotas_restantes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useracueducto',
            name='credito_interes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='useracueducto',
            name='credito_total_cuotas',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='useracueducto',
            name='credito_valor_cuota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='useracueducto',
            name='credito_valor_restante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='useracueducto',
            name='otros_gastos_cuotas_restantes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useracueducto',
            name='otros_gastos_interes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='useracueducto',
            name='otros_gastos_total_cuotas',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='useracueducto',
            name='otros_gastos_valor_cuota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='useracueducto',
            name='otros_gastos_valor_restante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
