# Generated by Django 4.2.1 on 2025-07-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acueducto', '0011_useracueducto_credito_cuotas_restantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='consumo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
